extraction:
  java:
    before_index:
      - wget -q https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
      - chmod a+x yq_linux_amd64
      - mv yq_linux_amd64 yq
      - export PATH="/opt/src:$PATH"
      # lgtm does a maven build so needs git-secrets
      - wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
      - tar -zxf git-secrets-1.3.0.tar.gz
      - cd git-secrets-1.3.0
      - export PATH="$PWD:$PATH"
    index:
    # Specify the Java version required to build the project.
      java_version: 12

