version: 2.1
executors:
  integration_test_exec:
    docker: # run the steps with Docker
      - image: cimg/openjdk:11.0.8
        environment:
          PGHOST: 127.0.0.1
    resource_class: medium+

common_filters: &common_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore:
        - gh-pages
workflows:
  version: 2
  everything:
    jobs:
      - integration-tests:
          <<: *common_filters
jobs:
  integration-tests:
    executor: integration_test_exec
    environment:
      TESTING_PROFILE: integration-tests
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: install pip
          command: |
            sudo apt update
            sudo apt install python3-distutils python3-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python3 get-pip.py
            # For debug purposes, a python3 version was installed in the image, pip is untagged
            python3 --version
            pip3 --version
      - run:
          name: install pip dependencies
          command: scripts/install-tests.sh
      - run:
          name: get hello world files
          command: |
            wget https://raw.githubusercontent.com/GA4GH-DREAM/dockstore-tool-helloworld/1.0.2/Dockstore.cwl
            wget https://raw.githubusercontent.com/GA4GH-DREAM/dockstore-tool-helloworld/1.0.2/test.json
            wget https://raw.githubusercontent.com/GA4GH-DREAM/dockstore-tool-helloworld/1.0.2/template.txt
            wget https://raw.githubusercontent.com/GA4GH-DREAM/dockstore-tool-helloworld/1.0.2/input.txt
      - run:
          nam: run cwltool
          command: cwltool Dockstore.cwl test.json