# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]
jobs:
  testWithSAMCLI:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install aws-sam-cli
     - name: Workaround for openapi.yaml
       run: cp --remove-destination dockstore-webservice/src/main/resources/openapi3/openapi.yaml wdl-parsing/WDLParsingFunction/openapi.yaml
     - name: Build with SAM CLI
       working-directory: ./wdl-parsing
       run:  sam build --use-container
     - name: Test with SAM CLI
       working-directory: ./wdl-parsing
       run:  sam local invoke -e events/event.json   


